#!/usr/bin/python3

import requests
import sys

def unshorten(link):
    if 'https://' not in link and 'http://' not in link:
        link = 'https://' + link
    try:
        session = requests.Session()
        response = session.head(link, allow_redirects=True)
        return response.url
    except:
        return "Unable to retrieve the target link"

if __name__ == '__main__':
    args = sys.argv
    concise = False

    if '-h' in args or '--help' in args:
        print('''Url unshortener written in Python
usage: unshorten URL [OPTIONS]

Options:
    -c, --concise       Show output in concise form (only the response url)
    -h, --help          Show this message and exit''')
        sys.exit(0)

    if '-c' in args or '--concise' in args:
        concise = True
        try:
            args.remove('-c')
        except: pass

        try: 
            args.remove('--concise')
        except: pass
        
    if len(sys.argv) == 1:
        print('No url provided: Exiting')
        sys.exit(0)

    url = sys.argv[1]
    target = unshorten(url)

    if concise:
        print(target)

    else:
        print(f'Provided url -> {url}')
        print(f'Unshortened url -> {target}')
